### ISSUE TITLE
Add support for adding qualifiers

### ISSUE THREAD

**Issue by larsgw** [maxlath/wikidata-edit#14]
For example the issue, volume and pages properties for publications.

**Comment by maxlath** [comment]
done!
* `qualifier.add`: 792ece6
* `qualifier.update`: a1e9407
* `qualifier.remove`: 934895b
* in `entity.edit`: 33007ff
* [how to](https://github.com/maxlath/wikidata-edit/blob/master/docs/how_to.md#qualifier)
