### ISSUE TITLE
Return value

### ISSUE THREAD

**Issue by mshd** [maxlath/wikidata-edit#25]
Hello after using `wdEdit.entity.create` how do I get the return value of the WIKIDATA entity that was created?
Appreciate any help :)

**Comment by maxlath** [comment]
`wdEdit.entity.create` should return a [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) resolving to the Wikidata API response, which includes the created entity data:
```js
wdEdit.entity.create(entityData)
.then(res => {
  // extracting our data using destructuring assignment
  // cf https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring
  const { entity } = res
  const { id, labels, descriptions, aliases, claims, sitelinks } = entity
  console.log('created entity id', id)
})
```

Does that answer your question?

(I added this to the documentation (66cb200))

**Comment by mshd** [comment]
Yes that's great, thanks a bunch :+1:
