### ISSUE TITLE
Can't add claim to custom wikibase

### ISSUE THREAD

**Issue by alemela** [maxlath/wikidata-edit#4]
This https://github.com/maxlath/wikidata-edit/blob/ae13c6d5923edd3c092f25ee76fa141e7777aad0/lib/properties/properties.js is an hard dependence.

Maybe you can write some words about on the README because could be problematic also for users that use this library just for Wikidata. In fact is not obvious that is better to run `scripts/update_properties` sometimes and the error if you are not update is a generic:
```
TypeError: Cannot read property 'type' of undefined
```

Moreover the script use `wd`. Is maybe a third part library?

Writing a custom list of property resolve the problem, but if you have a less handy solution it would be fantastic!

**Comment by maxlath** [comment]
`wd` is an executable [defined by `wikidata-cli`](https://github.com/maxlath/wikidata-cli/blob/master/package.json#L7)

I'm having a look at the rest of the issue

**Comment by maxlath** [comment]
I tried to make this process clearer: [Custom Wikibase instance](https://github.com/maxlath/wikidata-edit/blob/master/docs/use.md#custom-wikibase-instance). What do you think?

**Comment by alemela** [comment]
Thanks Maxime, the process is clearer! 

Unfortunately when you install wikibase you don't have also the SPARQL endpoint. (Even Wikidata added the SPARQL endpoint only after some years, and sometimes is not in sync with its own wikibase). So should be better if there is an API to fetch all the properties. Do you know if exists such API?

**Comment by maxlath** [comment]
You could get the entities from the [`wbgetentities`](https://www.wikidata.org/w/api.php?action=help&modules=wbgetentities) endpoint, but you would have to know/guess their ids first. Before the SPARQL endpoint was available, I was using it to get a list of all the properties by requesting all properties in the range `[P1..P${known last prop id}]`, but I think you can't get the property datatype from it, which is required by `wikidata-edit` to pre-validate claims.

**Comment by alemela** [comment]
I think the improvement you made are sufficient for know to let anyone understand it and use even with a custom wikibase, in some way. Thanks!
