### ISSUE TITLE
cannot guess syntax for monolingualtext properties

### ISSUE THREAD

**Issue by federicomorando** [maxlath/wikidata-edit#7]
I'm trying things like
`wdEdit.claim.add('Q61', 'P11', ["en", "a description"]);`
or
`wdEdit.claim.add('Q61', 'P11', { en: 'a new description'});`
where P11 is a Monolingualtext type property, but I cannot guess the correct syntax (while everything is OK for String and Item properties).
Could you please add an example of Monolingualtext property claim addition to the HowTo?
Thanks!!

**Comment by maxlath** [comment]
It was just not possible yet, now (v1.3.2) it is:
```js
wdEdit.claim.add('Q4115189', 'P1476', [ 'bulgroz', 'it' ])
```

**Comment by federicomorando** [comment]
Thanks, it works perfectly!
