### ISSUE TITLE
Invalid String due to regex test

### ISSUE THREAD

**Issue by alemela** [maxlath/wikidata-edit#9]
Hi Maxime!
Trying to edit a statement with a string like "foobar?" I've found an error.
Looking at the code the problem is the validation phase in https://github.com/maxlath/wikidata-edit/blob/master/lib/datatype_tests.js#L5 because ```\w``` is like ```[a-zA-Z0-9_]``` and is too restrictive.

Do you think this validation is necessary? For the moment I'm using ```.*```

Thanks!

**Comment by maxlath** [comment]
Hi!
I replaced it by a simple `_.isNonEmptyString` tests (590f9e1).
Thanks for reporting!
